---
abstract: 'Search for a file in an environment variable path'
author:
  - 'Tim Jenness E<lt>tjenness@cpan.orgE<gt>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.36'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-SearchPath
provides:
  File::SearchPath:
    file: lib/File/SearchPath.pm
    version: '0.07'
recommends:
  Env::Path: '0'
requires:
  File::Spec: '0.8'
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
  repository: git://github.com/timj/perl-File-SearchPath.git
version: '0.07'
